2016-06-20 15:07:58.419 -0600	START		Running Background1.feature
2016-06-20 15:07:58.428 -0600	LogError		i give <num1> to mickey
2016-06-20 15:07:58.429 -0600	Log		f	7	on_i_am_left_with_var	Background1.script<SOURCE>
2016-06-20 15:07:58.431 -0600	LogSuccess		I am left with <num2>
2016-06-20 15:07:58.433 -0600	LogError		i give <num1> to mickey
2016-06-20 15:07:58.434 -0600	Log		f	7	on_i_am_left_with_var	Background1.script<SOURCE>
2016-06-20 15:07:58.436 -0600	LogSuccess		I am left with <num2>
2016-06-20 15:07:58.438 -0600	LogError		i give <num1> to mickey
2016-06-20 15:07:58.438 -0600	Log		f	7	on_i_am_left_with_var	Background1.script<SOURCE>
2016-06-20 15:07:58.440 -0600	LogSuccess		I am left with <num2>
2016-06-20 15:07:58.441 -0600	EndTestCase		(Duration:"0.02044", Errors:"4", Exceptions:"0", StartTime:"2016-06-20 15:07:58 -0600", Successes:"3", TestCase:"Background1.feature", Warnings:"0")
2016-06-20 15:07:58.539 -0600	FAILURE	Screen_Error.png	3 scenarios (3 failed, 0 passed) 6 steps (3 failed, 0 skipped, 3 passed) Execution Time 0:00:00
